finance/urls.py
from django.contrib import admin
from django.urls import path
from .views import SupplierPaymentView, ShopPaymentView, PaymentLedgerSearchView

urlpatterns = [
    path('supplier-payment/', SupplierPaymentView.as_view()),
    path('shop-payment/', ShopPaymentView.as_view()),
    path('payment-ledger/search/', PaymentLedgerSearchView.as_view()),

]

myaccountant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import catalogue

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/product/', include("catalogue.urls")),
    path('admin/order/', include("order.urls")),
    path('admin/finance/', include("finance.urls")),
    path('admin/client/', include("client.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path
from .views import OrderCreateView, InvoiceView
from .adminviews import DatedSalesReport

urlpatterns = [
    path('order-create/', OrderCreateView.as_view()),
    path('display-invoice/', InvoiceView.as_view()),
    path('sales-report/', DatedSalesReport.as_view())
]

finance/models.py
from myaccountant.basemodels import BaseModel
from django.db import models


class PaymentLedger(BaseModel):
    SUPPLIER = 0
    SHOP = 1

    CLIENT_TYPE = ((SUPPLIER, "Supplier"),
                   (SHOP, "Shop"))
    CASH = 0
    CHEQUE = 1
    NEFT = 2
    PAYMENT_MODE = ((CASH, "Cash"),
                    (CHEQUE, "Cheque"),
                    (NEFT, "NEFT"))

    client_id = models.IntegerField()
    client_type = models.PositiveSmallIntegerField(choices=CLIENT_TYPE)
    paid_amount = models.DecimalField(max_digits=15, decimal_places=2)
    paid_at = models.DateTimeField(auto_now=True)
    payment_mode = models.PositiveSmallIntegerField(default=CASH, choices=PAYMENT_MODE)
    transaction_id = models.CharField(max_length=200, null=True, blank=True)

finance/forms.py
from django import forms
from .models import PaymentLedger


class PaymentDetailForm(forms.Form):

    client = forms.HiddenInput()
    client_name = forms.CharField()
    paid_amount = forms.DecimalField()
    payment_mode = forms.ChoiceField(choices=PaymentLedger.PAYMENT_MODE)
    payment_date = forms.DateTimeField(widget=forms.SelectDateWidget)
    transaction_id = forms.CharField(required=False)
    settle_account = forms.BooleanField(widget=forms.CheckboxInput, required=False)


class PaymentLedgerSearchForm(forms.Form):

    client_type = forms.ChoiceField(choices=PaymentLedger.CLIENT_TYPE)

finance/views.py
from decimal import Decimal
from myaccountant.baseviews import BaseAdminViews
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from .models import PaymentLedger
from .forms import PaymentDetailForm, PaymentLedgerSearchForm
from catalogue.models import Supplier
from client.models import Shop
from order.models import Order


class SupplierPaymentView(BaseAdminViews):

    template_name = "finance/pay_supplier.html"

    def get_context_data(self, **kwargs):
        return {"form": PaymentDetailForm()}

    def post(self, request):
        supplier_id = request.POST.get("client_id")
        amount = request.POST.get("paid_amount")
        paid_at = request.POST.get("payment_date")
        mode = request.POST.get("payment_mode")
        if not supplier_id:
            messages.error(request, "Suppler not found in system with ID: %s" % supplier_id)
            return self.render_to_response(self.get_context_data())

        supplier = Supplier.objects.get(id=supplier_id)
        PaymentLedger.objects.create(client_id=supplier_id, client_type=PaymentLedger.SUPPLIER,
                                     paid_amount=amount,
                                     # paid_at=paid_at,
                                     payment_mode=mode)
        # increasing supplier balance
        supplier.outstanding_balance -= Decimal(amount)
        supplier.save()
        messages.success(request, "Payment detail Updated, Final outstanding Balance for %s is %s" % (supplier.name, supplier.outstanding_balance))
        return self.render_to_response(self.get_context_data())


class ShopPaymentView(BaseAdminViews):

    template_name = "finance/shop_payment.html"

    def get_context_data(self, **kwargs):
        return {"form": PaymentDetailForm()}

    def post(self, request):
        supplier_id = request.POST.get("client_id")
        amount = request.POST.get("paid_amount")
        paid_at = request.POST.get("payment_date")
        mode = request.POST.get("payment_mode")
        if not supplier_id:
            messages.error(request, "Suppler not found in system with ID: %s" % supplier_id)
            return self.render_to_response(self.get_context_data())
        amount = Decimal(amount)
        shop = Shop.objects.get(id=supplier_id)
        PaymentLedger.objects.create(client_id=shop.id, client_type=PaymentLedger.SHOP,
                                     paid_amount=amount,
                                     # paid_at=paid_at,
                                     payment_mode=mode)
        # decreasing shop outstanding balance
        shop.outstanding_balance -= amount
        orders = Order.objects.filter(customer=shop, outstanding_amount__gt=Decimal(0))\
            .order_by('id')
        import ipdb;ipdb.set_trace()
        for o in orders:
            if amount <= 0:
                break
            if amount >= o.outstanding_amount:
                amount -= o.outstanding_amount
                o.outstanding_amount = Decimal(0)
            else:
                o.outstanding_amount -= amount
                amount = Decimal(0)
            o.save()

        shop.save()
        messages.success(request, "Payment detail Updated, Final outstanding Balance for %s is %s"
                         % (shop.name, shop.outstanding_balance))
        return self.render_to_response(self.get_context_data())


class PaymentLedgerSearchView(BaseAdminViews):

    template_name = "common/search.html"

    def get_context_data(self, **kwargs):
        return {"form": PaymentLedgerSearchForm(),
                "view_name": "Payment Ledger",
                "app": "finance"}

    def post(self, request):
        return HttpResponseRedirect("/admin/finance/paymentledger/?client_type=%s" %
                                    request.POST.get("client_type"))

templates/finance/pay_supplier.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block breadcrumbs %}
   <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">Home</a> >
        <a href="{% url 'admin:index' %}finance">Finance</a> >
        Supplier Payment
    </div>
{% endblock %}
{% block content %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
    $( function() {
        $( "#id_client_name" ).autocomplete({
          minLength: 3,
          select: function (event, ui) {
            $("#id_client").val(ui.item.pid);
            $("#id_client_name").val(ui.item.value);
            return false;
          },
          source:function(request, response){
            $.ajax({
                url: "/admin/product/supplier-autocomplete/?term=" + $("#id_client_name").val(),
                type: "GET",
                success: function (res) {
                    if (res.success){
                        if (res.data){
                            var results = [];
                            var data = res.data;
                            $.each(data, function(i, item) {
                                var itemToAdd = {
                                    pid : item.id,
                                    value : item.name
                                };
                                results.push(itemToAdd);
                            });
                            response(results);
                        }
                    }

                }
              });
           }
        });
  } );

</script>
<div id="content-main">
    <form id="payment-form" method="post" >
        {%csrf_token%}
        <table>
            <input type="hidden" id="id_client" name="client_id"/>
            {{form}}
            <tr>
                <td><input type="submit" value="Update Payment"/></td>
            </tr>
        </table>


    </form>
</div>
{% endblock %}

templates/finance/shop_payment.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block breadcrumbs %}
   <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">Home</a> >
        <a href="{% url 'admin:index' %}finance">Finance</a> >
        Shop Payment
    </div>
{% endblock %}
{% block content %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
    $( function() {
        $( "#id_client_name" ).autocomplete({
          minLength: 3,
          select: function (event, ui) {
            $("#id_client").val(ui.item.pid);
            $("#id_client_name").val(ui.item.value);
            return false;
          },
          source:function(request, response){
            $.ajax({
                url: "/admin/client/shop-autocomplete/?term=" + $("#id_client_name").val(),
                type: "GET",
                success: function (res) {
                    if (res.success){
                        if (res.data){
                            var results = [];
                            var data = res.data;
                            $.each(data, function(i, item) {
                                var itemToAdd = {
                                    pid : item.id,
                                    value : item.name + " (" + item.beat + ")"
                                };
                                results.push(itemToAdd);
                            });
                            response(results);
                        }
                    }

                }
              });
           }
        });
  } );

</script>
<div id="content-main">
    <form id="payment-form" method="post" >
        {%csrf_token%}
        <table>
            <input type="hidden" id="id_client" name="client_id"/>
            {{form}}
            <tr>
                <td><input type="submit" value="Update Payment"/></td>
            </tr>
        </table>


    </form>
</div>
{% endblock %}